name: dartpoet
description: You can use this library to programmatically generate dart file. Like Javapoet.
version: 1.0.3
homepage: https://github.com/Arxing/dart-dartpoet
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/dartpoet

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  xfile: ^1.0.2
  dart_style: ^1.2.10

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
